### ISSUE TITLE
Click `COMPILE` button in https://psvg.netlify.app/ but nothing happens

### ISSUE THREAD

**Issue by yihong0618** [LingDong-/psvg#1]
Hi~
Did I missed something.
![image](https://user-images.githubusercontent.com/15976103/99341240-7ebdc880-28c4-11eb-8522-90add62681bd.png)

**Comment by LingDong-** [comment]
Hi @yihong0618 ,

The compile button causes the graphics on the right to re-render, to reflect any changes made in the code editor in the left. From the screenshot it seems like the code is identical to the standard example, so it doesn't appear to do anything: it's already the correct rendering.

Maybe I should put a little status bar or something that says "compiled successfully!" :)

**Comment by yihong0618** [comment]
Got it, thank you~ :)
