### ISSUE TITLE
Exclude dist from source control

### ISSUE THREAD

**Issue by antfu** [LingDong-/psvg#12]
It's not ideal to keep dist files into the source control as it creates too much verbose and maybe potentially misalignment with the source. But having dist files could benefit users to grab and run without run into the install and build process. Or maybe we can guide users to download from npm or CDN dist instead: https://unpkg.com/@lingdong/psvg

What do you think?

**Comment by LingDong-** [comment]
I agree. Do npm/CDN automatically build the dist files? If so, then perfect, we can just put the links to those files in the README.

**Comment by 0918nobita** [comment]
I also agree. I knew `prepublishOnly` npm script for building the dist files is already set up.

**Comment by antfu** [comment]
> Do npm/CDN automatically build the dist files?

Yes. And if you don't mind, can I have the npm right to publish `@lingdong/psvg` so I can help manging the npm releases? (knowing you're busy :P) Thanks.

**Comment by LingDong-** [comment]
@antfu Awesome thanks! I added you as a maintainer on npm

**Comment by antfu** [comment]
Thanks. I will be going to remove the dist from git and update the corresponding readme.

**Comment by antfu** [comment]
Done. And released as v0.0.2. You may want to have a look at the readme to see if they match with your expectations.

**Comment by LingDong-** [comment]
Perfect. Thanks!
