### ISSUE TITLE
Lint & Code Formatting

### ISSUE THREAD

**Issue by 0918nobita** [LingDong-/psvg#14]
Why not introduce a Linter or code formatter to reduce trivial changes in code formatting and usage?

My recommendation:

- [ESLint](https://eslint.org/)
- [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint)
- [Prettier](https://prettier.io/)

**Comment by LingDong-** [comment]
I don't have a strong opinion about linters, if you make a pull request to install one I'd be happy to try it out! 

@antfu might have experience/preference?

**Comment by antfu** [comment]
Instead of a linter, maybe a formatter like Prettier would be enough at this moment. Prettier can be easier to use with only a few configurations. Would love to make a PR for it.
